---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-persistent-volume-claim
spec:
  storageClassName: mysql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---