---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/mysql-data/"
---