---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - name: mysql-port
    nodePort: 31006
    protocol: TCP
    port: 3306
    targetPort: 3306
---