apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: flask:latest
        imagePullPolicy: Never
        args:
        - /bin/sh
        - -c
        - cp application.py temp.py; python application.py
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '`/usr/bin/cmp -s /code/application.py /code/temp.py`'
          initialDelaySeconds: 5
          periodSeconds: 1
        name: flask
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: code
      restartPolicy: Always
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service.name: flask
status:
  loadBalancer: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: code
  labels:
    app: flask
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500m
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/code/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code
  labels:
    app: flask
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250m