---
- hosts: kubernetes
  gather_facts: yes
  become: yes

  vars:
    home: "{{ lookup('env','HOME') }}"
    user: "{{ lookup('env','USER') }}"
    swapfile_path: /swap
    kubernetes_version: '1.10'
    kubernetes_allow_pods_on_master: True
    docker_version: "17.03.0~ce-0"
    docker_package: "docker-ce={{ docker_version }}~ubuntu-xenial"
    docker_users:
      - "{{ user }}"
    k8s_definitions_path: "/vagrant/k8s-definitions/"  

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

    - name: Ensure swap is disabled.
      mount:
        path: "{{ swapfile_path }}"
        fstype: swap
        state: absent
    
    - name: Remove swap line on fstab
      lineinfile:
        path: /etc/fstab
        regexp: "swap"
        state: absent

    - name: Disable swap.
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

  tasks:
    - name: Build python app Docker image  
      command: "docker build -t flask ."
      args:
        chdir: /vagrant/python-app/
      register: python_app_docker_build
      changed_when: "'Installing' in python_app_docker_build.stdout"

    - name: Copy KUBECONFIG file to home path
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ home }}/admin.conf"
        remote_src: yes
        mode: 444
      
    - name: Add KUBECONFIG env to .bashrc
      lineinfile:
        path: '{{ home }}/.bashrc'
        line: 'export KUBECONFIG=~/admin.conf'
        state: present
    
    - name: Apply weaveworks network plugin
      command: kubectl apply -f weaveworks.yaml
      args:
        chdir: "{{ k8s_definitions_path }}"
      register: weaveworks_network_plugin
      changed_when: "'created' or 'configured' in weaveworks_network_plugin.stdout"    
    
    - name: Apply mysql 
      command: kubectl apply -f mysql/
      args:
        chdir: "{{ k8s_definitions_path }}"
      register: mysql
      changed_when: "'created' or 'configured' in mysql.stdout"
    
    - name: Apply python app
      command: "kubectl apply -f python-app/"
      args:
        chdir: "{{ k8s_definitions_path }}"
      register: pythonapp
      changed_when: "'created' or 'configured' in pythonapp.stdout"    