---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: python-mysql
spec:
  selector:
    matchLabels:
      app: python-mysql 
  replicas: 1
  template:
    metadata:
      labels:
        app: python-mysql
    spec:
      terminationGracePeriodSeconds: 1
      restartPolicy: Always
      containers:
      - name: python-mysql
        image: flask:latest
        imagePullPolicy: Never
        env:
          - name: MYSQL_USERNAME
            value: root 
          - name: MYSQL_PASSWORD
            value: vb7jKUVapNLyykBv 
          - name: MYSQL_INSTANCE_NAME
            value: root 
          - name: MYSQL_TCP_ADDR
            value: mysql.default.svc 
          - name: MYSQL_TCP_PORT
            value: "3306"
        ports:
        - containerPort: 3000
        args:
        - /bin/sh
        - -c
        - cp application.py temp.py; gunicorn --bind 0.0.0.0:3000 application:application
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '`/usr/bin/cmp -s /code/application.py /code/temp.py`'
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 256Mi
        volumeMounts:
        - mountPath: /code
          name: code
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
status: {}
---