---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: code
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/vagrant/python-app/"
---