---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - name: web
    nodePort: 31050
    protocol: TCP
    port: 80
    targetPort: 5000
---