---
apiVersion: v1
kind: Service
metadata:
  name: python-mysql
  labels:
    app: python-mysql
spec:
  type: NodePort
  selector:
    app: python-mysql
  ports:
  - name: python-mysql-port
    nodePort: 31000
    protocol: TCP
    port: 80
    targetPort: 3000
---